name: Maurine Dodge Photography
layout_spectrum: 0.10648459973560628
typography_spectrum: 0.5422602611207542
analytics:
  facebook: '1788863521350364'
  google: UA-78600613-1
color:
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  brandStrength: 0.8826383425528644
  lightness: 0.5878445656898219
  saturation: 0.2838043847929982
  rhythmicContrast: 0.7665333621650197
purpose: []
title: Exploring the world ....
description: ' one click at a time.'
author:
  name: Maurine Dodge
  url: 'https://www.facebook.com/silvatungfox'
  email: silvatungfox@gmail.com
navigation:
  - name: 'Chicago '
    url: 'https://thegrid.ai/chicago-82769/?cache=no'
    type: external
  - name: Lady Filmmakers Festival
    url: 'https://thegrid.ai/lady-filmmakers-festival-shelby/?cache=no'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/ed307f587f12555cc158a77a205e2a639b9ccaed.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/ed307f587f12555cc158a77a205e2a639b9ccaed.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: s3-us-west-2.amazonaws.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
