layout_spectrum: 0.6790604507650184
typography_spectrum: 0.43322535183824745
color:
  brandStrength: 0.5535828556358299
  lightness: 0.5136799534832561
  saturation: 0.4267180012454196
  rhythmicContrast: 0.6938436271231805
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
analytics:
  google: UA-78600613-1
  facebook: '1788863521350364'
author:
  name: Maurine Dodge
  email: silvatungfox@gmail.com
  url: 'https://www.facebook.com/silvatungfox'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2eb158b-a59e-40dd-862f-c323801e3c61.svg
name: Maurine Dodge Photography
navigation:
  - name: Castles
    id: a1d12c8e-e249-4b9e-8a05-3fa670ef9d6e
    type: content
title: Exploring the world and the people in it....
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/3d6e737db270eb1fdefd0ffc11a307051853682a.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/3d6e737db270eb1fdefd0ffc11a307051853682a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: capturing moments one click at a time.
github: true
